### ISSUE TITLE
Question about system metrics

### ISSUE THREAD

**Issue by anderslemke** [miketheman/heroku-buildpack-datadog#27]
Hi Mike,

Thanks for great buildpack. ❤️

I have a question about system metrics.
I don't seem to get any metrics for eg. `system.mem.usable` in Datadog.

Do you know why that is?
Is this something I can switch on?

**Comment by miketheman** [comment]
Hi @anderslemke,
Thanks!

This buildpack is designed to only collect application-emitted Statsd metrics and forward them along to Datadog.
Since Heroku Dynos are slightly different than a normal container/server, not all of the interfaces for collection are available.

If you're looking for runtime metrics, cpu, memory, etc - these are typically emitted by Heroku's Log stream, and you can add a drain dyno that funnels those to Datadog.
See these two projects:
- https://github.com/ozinc/heroku-datadog-drain (NodeJS)
- https://github.com/apiaryio/heroku-datadog-drain-golang (Golang)

Hope this helps!

**Comment by anderslemke** [comment]
Perfect! Thanks for taking the time to answer.
